### ISSUE TITLE
install extentions ,mission tab.scss 

### ISSUE THREAD

**Issue by greper** [HFAiLab/jupyterlab_tensorboard_pro#11]
install extentions  and run rebuild, i get an error: 

```
(base) jovyan@tf-gpu-mnist-0:~/start-mnist/mnist$ jupyter lab build
[LabBuildApp] JupyterLab 3.4.3
[LabBuildApp] Building in /opt/conda/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (production, minimized)
Build failed.
Troubleshooting: If the build failed due to an out-of-memory error, you
may be able to fix it by disabling the `dev_build` and/or `minimize` options.

If you are building via the `jupyter lab build` command, you can disable
these options like so:

jupyter lab build --dev-build=False --minimize=False

You can also disable these options for all JupyterLab builds by adding these
lines to a Jupyter config file named `jupyter_config.py`:

c.LabBuildApp.minimize = False
c.LabBuildApp.dev_build = False

If you don't already have a `jupyter_config.py` file, you can create one by
adding a blank file of that name to any of the Jupyter config directories.
The config directories can be listed by running:

jupyter --paths

Explanation:

- `dev-build`: This option controls whether a `dev` or a more streamlined
`production` build is used. This option will default to `False` (i.e., the
`production` build) for most users. However, if you have any labextensions
installed from local files, this option will instead default to `True`.
Explicitly setting `dev-build` to `False` will ensure that the `production`
build is used in all circumstances.

- `minimize`: This option controls whether your JS bundle is minified
during the Webpack build, which helps to improve JupyterLab's overall
performance. However, the minifier plugin used by Webpack is very memory
intensive, so turning it off may help the build finish successfully in
low-memory environments.

An error occurred.
RuntimeError: JupyterLab failed to build
See the log file for details:  /tmp/jupyterlab-debug-xki2wilg.log
(base) jovyan@tf-gpu-mnist-0:~/start-mnist/mnist$ cat /tmp/jupyterlab-debug-xki2wilg.log
[LabBuildApp] Building in /opt/conda/share/jupyter/lab
[LabBuildApp] Node v14.20.1

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (production, minimized)
[LabBuildApp] > node /opt/conda/lib/python3.8/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.69s.

[LabBuildApp] > node /opt/conda/lib/python3.8/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
[LabBuildApp] yarn run v1.21.1
$ /opt/conda/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
Done in 0.43s.

[LabBuildApp] > node /opt/conda/lib/python3.8/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
[LabBuildApp] yarn run v1.21.1
$ webpack --config webpack.prod.minimize.config.js
[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve './tab.scss' in '/opt/conda/share/jupyter/lab/staging/node_modules/jupyterlab_tensorboard_pro/style'
    at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:1768:28
    at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:742:13
    at eval (eval at create (/opt/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:276:22
    at eval (eval at create (/opt/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:405:22
    at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:119:11
    at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:650:24
    at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:813:8
    at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:933:5
resolve './tab.scss' in '/opt/conda/share/jupyter/lab/staging/node_modules/jupyterlab_tensorboard_pro/style'
  using description file: /opt/conda/share/jupyter/lab/staging/node_modules/jupyterlab_tensorboard_pro/package.json (relative path: ./style)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /opt/conda/share/jupyter/lab/staging/node_modules/jupyterlab_tensorboard_pro/package.json (relative path: ./style/tab.scss)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /opt/conda/share/jupyter/lab/staging/node_modules/jupyterlab_tensorboard_pro/style/tab.scss doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /opt/conda/share/jupyter/lab/staging/node_modules/jupyterlab_tensorboard_pro/style/tab.scss.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /opt/conda/share/jupyter/lab/staging/node_modules/jupyterlab_tensorboard_pro/style/tab.scss.json doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /opt/conda/share/jupyter/lab/staging/node_modules/jupyterlab_tensorboard_pro/style/tab.scss.wasm doesn't exist
      as directory
        /opt/conda/share/jupyter/lab/staging/node_modules/jupyterlab_tensorboard_pro/style/tab.scss doesn't exist
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/opt/conda/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/opt/conda/lib/python3.8/site-packages/jupyterlab/labapp.py", line 196, in start
    raise e

[LabBuildApp]   File "/opt/conda/lib/python3.8/site-packages/jupyterlab/labapp.py", line 187, in start
    build(

[LabBuildApp]   File "/opt/conda/lib/python3.8/site-packages/jupyterlab/commands.py", line 498, in build
    return handler.build(

[LabBuildApp]   File "/opt/conda/lib/python3.8/site-packages/jupyterlab/commands.py", line 713, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab
```

when i copy  tab.scss into  `/opt/conda/share/jupyter/lab/staging/node_modules/jupyterlab_tensorboard_pro/style`

I get this :

```
WARNING in license-webpack-plugin: could not find any license file for jsonify. Use the licenseTextOverrides option to add the license text if desired.

ERROR in ./node_modules/jupyterlab_tensorboard_pro/style/tab.scss 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> .tensorboard-ng-creator {
|   display: flex;
|   width: 100%;
 @ ./node_modules/jupyterlab_tensorboard_pro/style/index.js 2:0-20
 @ ./build/style.js
 @ ./build/index.out.js 27:0-20
 @ ./build/bootstrap.js

webpack 5.44.0 compiled with 1 error and 112 warnings in 80706 ms

asset index.css 15.9 KiB [compared for emit] (name: index)
asset index.js 0 bytes [compared for emit] [minimized] (name: index)
Entrypoint index 15.9 KiB = index.css 15.9 KiB index.js 0 bytes
./node_modules/@jupyterlab/theme-dark-extension/style/theme.css 50 bytes [built] [code generated]
css ./node_modules/css-loader/dist/cjs.js!./node_modules/@jupyterlab/theme-dark-extension/style/variables.css 15.4 KiB [code generated]
css ./node_modules/css-loader/dist/cjs.js!./node_modules/@jupyterlab/theme-dark-extension/style/theme.css 472 bytes [code generated]
webpack 5.44.0 compiled successfully in 2032 ms

asset index.css 14.8 KiB [compared for emit] (name: index)
asset index.js 0 bytes [compared for emit] [minimized] (name: index)
Entrypoint index 14.8 KiB = index.css 14.8 KiB index.js 0 bytes
./node_modules/@jupyterlab/theme-light-extension/style/theme.css 50 bytes [built] [code generated]
css ./node_modules/css-loader/dist/cjs.js!./node_modules/@jupyterlab/theme-light-extension/style/variables.css 14.3 KiB [code generated]
css ./node_modules/css-loader/dist/cjs.js!./node_modules/@jupyterlab/theme-light-extension/style/theme.css 472 bytes [code generated]
webpack 5.44.0 compiled successfully in 2024 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/opt/conda/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/opt/conda/lib/python3.8/site-packages/jupyterlab/labapp.py", line 196, in start
    raise e

[LabBuildApp]   File "/opt/conda/lib/python3.8/site-packages/jupyterlab/labapp.py", line 187, in start
    build(

[LabBuildApp]   File "/opt/conda/lib/python3.8/site-packages/jupyterlab/commands.py", line 498, in build
    return handler.build(

[LabBuildApp]   File "/opt/conda/lib/python3.8/site-packages/jupyterlab/commands.py", line 713, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab
```

**Comment by aircloud** [comment]
This problem does exist because jupyter cannot load scss correctly. According to https://github.com/jupyterlab/jupyterlab/issues/7502, it is a feature of jupyter.

Later, I will consider eliminating scss at an earlier stage, although I think it may not be very flexible.

At present, I think that `jupyter lab build` is not a high-frequency command? You can consider uninstalling this plugin, run `jupyter lab build` and then reinstalling it.

**Comment by greper** [comment]
After installing the extension with the ui and rebuilding, I got an installation error, prompted me to run `jupyter lab build` for detailed error information ,The above error occurred  when I ran `jupyter lab build` command.

**Comment by aircloud** [comment]
Command line installation is preferred

>In fact, I tried to use the UI to install, and it should prompt that the installation is not possible:
![iShot2022-11-12 14 25 33](https://user-images.githubusercontent.com/10907228/201460761-10e4cc9d-30cc-434e-800e-75a8d785a763.png)

**Comment by aircloud** [comment]
close the issue because of no update or no one else seems to have similar questions
