### ISSUE TITLE
是否对TensorBoard有版本限制？

### ISSUE THREAD

**Issue by D-Walter** [HFAiLab/jupyterlab_tensorboard_pro#12]
```
[E 2022-11-18 02:13:00.859 ServerApp] Uncaught exception POST /api/tensorboard_pro?1668708762952 (172.18.69.18)
    HTTPServerRequest(protocol='http', host='10.32.90.201:8888', method='POST', uri='/api/tensorboard_pro?1668708762952', version='HTTP/1.1', remote_ip='172.18.69.18')
    Traceback (most recent call last):
      File "/home/cv2/miniconda3/envs/jupyterlab/lib/python3.9/site-packages/tornado/web.py", line 1711, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/cv2/miniconda3/envs/jupyterlab/lib/python3.9/site-packages/tornado/web.py", line 3208, in wrapper
        return method(self, *args, **kwargs)
      File "/home/cv2/miniconda3/envs/jupyterlab/lib/python3.9/site-packages/jupyterlab_tensorboard_pro/api_handlers.py", line 41, in post
        self.settings["tensorboard_manager"]
      File "/home/cv2/miniconda3/envs/jupyterlab/lib/python3.9/site-packages/jupyterlab_tensorboard_pro/tensorboard_manager.py", line 145, in new_instance
        create_tb_app(
      File "/home/cv2/miniconda3/envs/jupyterlab/lib/python3.9/site-packages/jupyterlab_tensorboard_pro/tensorboard_manager.py", line 71, in create_tb_app
        return manager.add_instance(logdir, reload_interval, standard_tensorboard_wsgi(
      File "/home/cv2/miniconda3/envs/jupyterlab/lib/python3.9/site-packages/jupyterlab_tensorboard_pro/tensorboard_manager.py", line 68, in standard_tensorboard_wsgi
        return application.TensorBoardWSGIApp(flags, plugin_loaders, ingester.data_provider,
      File "/home/cv2/miniconda3/envs/jupyterlab/lib/python3.9/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 142, in TensorBoardWSGIApp_2x
        path_to_run = application.parse_event_files_spec(logdir)
    AttributeError: module 'tensorboard.backend.application' has no attribute 'parse_event_files_spec'
```

使用版本为TensorBoard==2.10.1

**Comment by D-Walter** [comment]
删除jupyter_tensorboard即正常，不知哪一步引入了这个包，如该包非您的项目引入并且不必要，请您关闭该issue，感谢您的工作。

**Comment by aircloud** [comment]
jupyter_tensorboard 是需要删除的，这个包并非本项目的依赖，是另外一个 tensorboard 插件的实现（ jupyter_tensorboard 只支持 notebook）
