### ISSUE TITLE
安装插件后，一直显示initializing

### ISSUE THREAD

**Issue by electroram** [HFAiLab/jupyterlab_tensorboard_pro#18]
![image](https://github.com/HFAiLab/jupyterlab_tensorboard_pro/assets/37216707/aba6cca0-c2a7-4841-adac-e4c14fbdca08)

我安装了插件之后一直在initializing
我的环境是
python:3.7
TensorFlow-gpu=2.3.1
IPython          : 8.13.2
ipykernel        : 6.23.0
ipywidgets       : 8.0.6
jupyter_client   : 8.2.0
jupyter_core     : 5.3.0
jupyter_server   : 2.5.0
jupyterlab       : 3.6.3
nbclient         : 0.7.4
nbconvert        : 7.4.0
nbformat         : 5.8.0
notebook         : 6.5.4
qtconsole        : 5.4.3
traitlets        : 5.9.0

注：我是在服务器中部署的，拉取的images是：jupyter/datascience-notebook:2023-05-15
_Originally posted by @electroram in https://github.com/HFAiLab/jupyterlab_tensorboard_pro/issues/17#issuecomment-1563655577_

**Comment by electroram** [comment]
### 安装插件之后显示了这个错误：
        If you are experiencing the build failure after installing an extension (or trying to include previously installed extension after updating JupyterLab) please check the extension repository for new installation instructions as many extensions migrated to the prebuilt extensions system which no longer requires rebuilding JupyterLab (but uses a different installation procedure, typically involving a package manager such as 'pip' or 'conda').

        If you specifically intended to install a source extension, please run 'jupyter lab build' on the server for full output.

### 运行了jupyter lab build之后又出现了这个错误：
[LabBuildApp] JupyterLab 3.6.3
[LabBuildApp] Building in /opt/conda/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (production, minimized)
Build failed.
Troubleshooting: If the build failed due to an out-of-memory error, you
may be able to fix it by disabling the `dev_build` and/or `minimize` options.

If you are building via the `jupyter lab build` command, you can disable
these options like so:

jupyter lab build --dev-build=False --minimize=False

You can also disable these options for all JupyterLab builds by adding these
lines to a Jupyter config file named `jupyter_config.py`:

c.LabBuildApp.minimize = False
c.LabBuildApp.dev_build = False

If you don't already have a `jupyter_config.py` file, you can create one by
adding a blank file of that name to any of the Jupyter config directories.
The config directories can be listed by running:

jupyter --paths

Explanation:

- `dev-build`: This option controls whether a `dev` or a more streamlined
`production` build is used. This option will default to `False` (i.e., the
`production` build) for most users. However, if you have any labextensions
installed from local files, this option will instead default to `True`.
Explicitly setting `dev-build` to `False` will ensure that the `production`
build is used in all circumstances.

- `minimize`: This option controls whether your JS bundle is minified
during the Webpack build, which helps to improve JupyterLab's overall
performance. However, the minifier plugin used by Webpack is very memory
intensive, so turning it off may help the build finish successfully in
low-memory environments.

An error occurred.
RuntimeError: JupyterLab failed to build
See the log file for details:  /tmp/jupyterlab-debug-tkis9x15.log

### 查看了日志后看到：
**(base) jovyan@18ba5171b0d0:~/work/HyperPose$ cat /tmp/jupyterlab-debug-tkis9x15.log**

[LabBuildApp] Building in /opt/conda/share/jupyter/lab
[LabBuildApp] Node v16.19.0

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (production, minimized)
[LabBuildApp] > node /opt/conda/lib/python3.10/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.95s.

[LabBuildApp] > node /opt/conda/lib/python3.10/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
[LabBuildApp] yarn run v1.21.1
$ /opt/conda/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
Done in 0.67s.

[LabBuildApp] > node /opt/conda/lib/python3.10/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
[LabBuildApp] yarn run v1.21.1
$ webpack --config webpack.prod.minimize.config.js
[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve './tab.scss' in '/opt/conda/share/jupyter/lab/staging/node_modules/jupyterlab_tensorboard_pro/style'
    at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:1768:28
    at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:742:13
    at eval (eval at create (/opt/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:276:22
    at eval (eval at create (/opt/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:405:22
    at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:119:11
    at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:650:24
    at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:813:8
    at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:933:5
resolve './tab.scss' in '/opt/conda/share/jupyter/lab/staging/node_modules/jupyterlab_tensorboard_pro/style'
  using description file: /opt/conda/share/jupyter/lab/staging/node_modules/jupyterlab_tensorboard_pro/package.json (relative path: ./style)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /opt/conda/share/jupyter/lab/staging/node_modules/jupyterlab_tensorboard_pro/package.json (relative path: ./style/tab.scss)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /opt/conda/share/jupyter/lab/staging/node_modules/jupyterlab_tensorboard_pro/style/tab.scss doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /opt/conda/share/jupyter/lab/staging/node_modules/jupyterlab_tensorboard_pro/style/tab.scss.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /opt/conda/share/jupyter/lab/staging/node_modules/jupyterlab_tensorboard_pro/style/tab.scss.json doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /opt/conda/share/jupyter/lab/staging/node_modules/jupyterlab_tensorboard_pro/style/tab.scss.wasm doesn't exist
      as directory
        /opt/conda/share/jupyter/lab/staging/node_modules/jupyterlab_tensorboard_pro/style/tab.scss doesn't exist
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/opt/conda/lib/python3.10/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/opt/conda/lib/python3.10/site-packages/jupyterlab/labapp.py", line 204, in start
    raise e

[LabBuildApp]   File "/opt/conda/lib/python3.10/site-packages/jupyterlab/labapp.py", line 195, in start
    build(

[LabBuildApp]   File "/opt/conda/lib/python3.10/site-packages/jupyterlab/commands.py", line 506, in build
    return handler.build(

[LabBuildApp]   File "/opt/conda/lib/python3.10/site-packages/jupyterlab/commands.py", line 722, in build
    raise RuntimeError(msg)
[LabBuildApp] RuntimeError: JupyterLab failed to build
[LabBuildApp] Exiting application: JupyterLab

**Comment by aircloud** [comment]
这个插件使用了 scss，根据 jupyterlab 的 [issue](https://github.com/jupyterlab/jupyterlab/issues/7502), 不支持 `jupyter lab build`，直接安装应该是不需要  `jupyter lab build` 这个过程的。

一直 initializing 一般是 tensorboard 后端启动的过程报错了，可以开启 debug 日志看看？

**Comment by ningxiaokai** [comment]
拉下dev分枝后，yarn install 就会报错，网上搜索的都试了没啥用，麻烦看看这个是啥问题，就是前端去改完代码的话，如何才能测试jupyter是否改了能看到效果
![image](https://github.com/HFAiLab/jupyterlab_tensorboard_pro/assets/105834888/c11db89c-c7e0-4572-bd3b-2a6488cd0b01)

**Comment by shayuxiao** [comment]
![1ddfdc5c-d067-48ae-892f-1df9b22a8358](https://github.com/HFAiLab/jupyterlab_tensorboard_pro/assets/105834888/13d02933-c408-4ec3-9f00-e71ec87feafd)


yarn install 报错

**Comment by zhanglijun95** [comment]
我也遇到了同样的问题，直接pip install之后，重启了jupyterlab再在launcher里打开tensorboard，但是一直initilizing，请问应该怎么解决呢？
